# Generated by Django 6.0.7 on 2026-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('offer', 'Offer')], default='applied', max_length=20)),
                ('date_applied', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('job_link', models.URLField(blank=True)),
            ],
        ),
    ]
